name: Auto Rotate Secrets
on:
  schedule:
    - cron: "0 0 1 * *" # co miesiąc
jobs:
  rotate-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Rotate JWT/API keys
        run: |
          bash scripts/deployment/rotate_keys.sh
      - name: Update K8s ExternalSecret
        run: |
          kubectl rollout restart deployment/inference-service
      - name: Notify
        run: echo "Secrets rotation completed"